server:
  port: 8080
spring:
  datasource:
    master:
      #url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver



  #thymeleaf配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #关闭缓存 默认为true
    cache: false

#mybatis配置
mybatis:
  #映射文件所在的路径
  mapper-locations: classpath:mappers/*.xml
  #POJO类所在的包
  type-aliases-package: com.fsw.springbootpro.pojo

#分页插件配置
pagehelper:
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  helper-dialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  #pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
  #自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #这个配不配都行，默认就是这个
  params: count=countsql
